/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static ArrayList<Game> multiplayer = new ArrayList<Game>();
    public static void main(String[] args) {

// Set up
        WordChooser word_chooser = new WordChooser();
        Masker masker = new Masker();
        Scanner scanner = new Scanner(System.in);
        
        // Game 1
        
        Game game1 = new Game(word_chooser);
        multiplayer.add(game1);
        
        System.out.println(game1.getWordToGuess(masker));
        
        while(game1.getRemainingAttempts() != 0 && game1.GameWon()==false){
            System.out.println(String.format("Player 1: Enter one letter to guess (%d attempts remaining)", game1.getRemainingAttempts()));
            Character guess = scanner.nextLine().charAt(0);
            game1.guessLetter(guess);
            if(game1.GameLost()== true){
                System.out.println("0 Attempts remaining. You lose!");
            } else{
                System.out.println(game1.getWordToGuess(masker));
            }
            if(game1.GameWon()==true){
                System.out.println("You win!");
            }
        }
        // Game 2
        
        Game game2 = new Game(word_chooser);
        multiplayer.add(game2);

        System.out.println(game2.getWordToGuess(masker));
        
        while(game2.getRemainingAttempts() != 0 && game2.GameWon()==false){
            System.out.println(String.format("Player 2: Enter one letter to guess (%d attempts remaining)", game2.getRemainingAttempts()));
            Character guess = scanner.nextLine().charAt(0);
            game2.guessLetter(guess);
            if(game2.GameLost()== true){
                System.out.println("0 Attempts remaining. You lose!");
            } else{
                System.out.println(game2.getWordToGuess(masker));
            }
            if(game2.GameWon()==true){
                System.out.println("You win!");
            }
            }
    }
}

